version: 0.2

phases:
  install:
    commands:
      # install node 12 and npm
      - apt-get update
      - apt-get upgrade -y
      - echo Installing Node 12 and npm...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      # tests
      - echo Testing...
      # build
      - echo Building...
      - npm run build
      # Listing files
      - ls build
      # Copy appscpec into the build folder
      - mv appspec.yml build/
      - ls build/
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
