  development[m
  editable-table[m
  feat/request-history-editableTable[m
  feat/setting-instructor-request[m
  feat/setting-provider-request[m
  feat/type-services[m
  feature/client-confirm-request[m
  feature/managing-services[m
  feature/operario-setting-request[m
  feature/perfil-operario[m
  feature/requests-context[m
  feature/sending-emails[m
  feature/services-lines[m
  feature/users-administration[m
  fix/client-request-single-page[m
  fix/hot-asked-fixes[m
* [32mfix/hot-fixes[m
  fix/reset-password-form[m
  gender-field-registration[m
  help[m
  master[m
  [31mremotes/origin/development[m
  [31mremotes/origin/feat/profile-edit[m
  [31mremotes/origin/feat/service-request-notifications[m
  [31mremotes/origin/feat/tracks-list[m
  [31mremotes/origin/feat/user-credits[m
  [31mremotes/origin/feature/client-confirm-request[m
  [31mremotes/origin/feature/google-maps[m
  [31mremotes/origin/feature/operario-setting-request[m
  [31mremotes/origin/feature/profile-tacnico[m
  [31mremotes/origin/feature/sending-emails[m
  [31mremotes/origin/feature/services-lines[m
  [31mremotes/origin/feature/super-client[m
  [31mremotes/origin/fix/74[m
  [31mremotes/origin/fix/cancelarion-terms[m
  [31mremotes/origin/fix/client-request-single-page[m
  [31mremotes/origin/fix/hot-asked-fixes[m
  [31mremotes/origin/fix/hot-fixes[m
  [31mremotes/origin/fix/request-toasts[m
  [31mremotes/origin/fix/requests-edit-credits[m
  [31mremotes/origin/fix/requests-socket[m
  [31mremotes/origin/fix/reset-password-form[m
  [31mremotes/origin/fix/toast-styles[m
  [31mremotes/origin/fix/track-picture[m
  [31mremotes/origin/hotfix/requests-context-update[m
  [31mremotes/origin/master[m
  [31mremotes/origin/revert-76-fix/74[m
  [31mremotes/origin/revert-77-revert-76-fix/74[m
  [31mremotes/origin/revert-94-feat/service-request-notifications[m
