export * from './Home/Home';
export * from './Historial/Historial';
export * from './Login/Login';
export * from './PasswordRecover/PasswordRecover';
export * from './Calendar/Calendar';
export * from './Pistas/Pistas';
export * from './Instructores/Instructores';
export * from './Proveedores/Proveedores';
export * from './SingleRequestAdmin/SingleRequestAdmin';
